// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persona.API.Model;

namespace Persona.API.Migrations
{
    [DbContext(typeof(PersonaContext))]
    [Migration("20200506030642_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Persona.API.Model.Contacto", b =>
                {
                    b.Property<int>("IdDoc")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoContacto")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nchar(200)")
                        .IsFixedLength(true)
                        .HasMaxLength(200);

                    b.HasKey("IdDoc", "IdTipoContacto")
                        .HasName("PK__Contacto__C92D3B36AD16FC3D");

                    b.ToTable("Contacto");
                });

            modelBuilder.Entity("Persona.API.Model.Persona", b =>
                {
                    b.Property<int>("IdDoc")
                        .HasColumnType("int");

                    b.Property<int?>("Edad")
                        .HasColumnType("int");

                    b.Property<int?>("IdPais")
                        .HasColumnType("int");

                    b.Property<int?>("IdTipoDoc")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nchar(200)")
                        .IsFixedLength(true)
                        .HasMaxLength(200);

                    b.Property<string>("Sexo")
                        .HasColumnType("char(1)")
                        .IsFixedLength(true)
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.HasKey("IdDoc")
                        .HasName("PK__Persona__5EACE01C794D0B1D");

                    b.ToTable("Persona");
                });

            modelBuilder.Entity("Persona.API.Model.Relacion", b =>
                {
                    b.Property<int>("IdDoc1")
                        .HasColumnType("int");

                    b.Property<int>("IdDoc2")
                        .HasColumnType("int");

                    b.Property<int>("IdRelacion")
                        .HasColumnType("int");

                    b.HasKey("IdDoc1", "IdDoc2")
                        .HasName("PK__Relacion__2E9D386BF7281ECC");

                    b.ToTable("Relacion");
                });
#pragma warning restore 612, 618
        }
    }
}
